/**
 * Generate the content for .cotext/COTEXT_GUIDE.md
 * This is the single source of truth for agents working with this repo.
 */
export function generateCotextGuide(repoOwner: string, repoName: string, rooms: Array<{ path: string }>): string {
  const roomList = rooms.map(r => `- \`${r.path}\` → \`${r.path}/.cotext/cotext.md\``).join('\n');
  
  return `# COTEXT_GUIDE.md

> Auto-generated by Cotext. This file is the single source of truth for agents working with this repository.
> Do not edit manually — Cotext will overwrite on next sync.

## 1. What is Cotext?

Cotext is a context engineering tool. This repository (\`${repoOwner}/${repoName}\`) is used as a **context pool** — a structured collection of notes, decisions, and context blocks stored as markdown files.

**The repository is the single source of truth.** All agents must read from and write back to this repo.

## 2. Structure

\`\`\`
<directory>/.cotext/cotext.md   ← Context file (one per directory/room)
<directory>/.cotext/assets/     ← Attached images and files
.cotext/COTEXT_GUIDE.md         ← This file (guide for agents)
.cotext/INDEX.md                ← Room index and map
\`\`\`

### Active Rooms
${roomList || '- No rooms configured yet'}

## 3. Block Format

Each entry ("block") in a cotext.md file follows this format:

\`\`\`markdown
## YYYY-MM-DD HH:mm
<!-- source: me -->

Your content here (markdown).

Attachments:
- ![image](./assets/filename.webp)
\`\`\`

### Source Tags (Provenance)
- \`source: me\` — Written by a human through Cotext UI (includes copy-pasted AI outputs chosen by the user)
- \`source: agent\` — Written by a connected agent via MCP/API
- \`source: chatgpt\` / \`source: claude\` / \`source: gemini\` — Written by a specific AI agent

**Rule: Never omit the source tag.** This enables filtering human thoughts vs AI-generated content.

## 4. Reading Order

1. \`.cotext/COTEXT_GUIDE.md\` (this file)
2. \`.cotext/INDEX.md\` (room map)
3. The specific room's \`cotext.md\` file

## 5. Mandatory Protocol

\`\`\`
1. git pull          ← Always pull latest before reading/writing
2. Read context      ← Read GUIDE → INDEX → room cotext.md
3. Write blocks      ← Follow the block format above (type, tags, source)
4. git push          ← Push your changes back to the repo
\`\`\`

## 6. Rules

- **Always tag your source**: Use \`<!-- source: agent -->\` (or your specific model name) for content you generate.
- **Never mix**: Don't inject AI-generated content without a source tag.
- **Pull before push**: Always pull the latest content before making changes.
- **Append only**: Add new blocks at the end. Don't modify existing blocks unless explicitly asked.
- **Respect existing content**: The human's blocks (\`source: me\`) are primary. Don't summarize or rewrite them.
`;
}

/**
 * Generate the content for .cotext/INDEX.md
 * A machine-readable map of rooms and their metadata.
 */
export function generateCotextIndex(repoOwner: string, repoName: string, rooms: Array<{ path: string; updatedAt?: string }>): string {
  const roomEntries = rooms.map(r => {
    const updated = r.updatedAt ? ` (updated: ${r.updatedAt.split('T')[0]})` : '';
    return `- [${r.path}](${r.path}/.cotext/cotext.md)${updated}`;
  }).join('\n');

  return `# Cotext Index — ${repoOwner}/${repoName}

> Auto-generated by Cotext. Do not edit manually.

## Rooms
${roomEntries || '- No rooms yet'}
`;
}

/**
 * Generate the thin pointer block for AGENTS.md or CLAUDE.md
 * Uses <!-- cotext:start --> markers for non-destructive updates.
 */
export function generateAgentsPointerBlock(): string {
  return `<!-- cotext:start -->
## Cotext Context Pool

This repository uses [Cotext](https://cotext-app.vercel.app) as a context engineering tool.

**Start here:** Read \`.cotext/COTEXT_GUIDE.md\` for structure, block format, and the mandatory pull/push protocol.

- Guide: \`.cotext/COTEXT_GUIDE.md\`
- Index: \`.cotext/INDEX.md\`
- Rooms: Each directory with \`.cotext/cotext.md\`
<!-- cotext:end -->`;
}

/**
 * Insert or update the Cotext pointer block in an existing file's content.
 * If markers exist, replace the block between them. Otherwise, append.
 */
export function upsertPointerBlock(existingContent: string, pointerBlock: string): string {
  const startMarker = '<!-- cotext:start -->';
  const endMarker = '<!-- cotext:end -->';
  const startIdx = existingContent.indexOf(startMarker);
  const endIdx = existingContent.indexOf(endMarker);

  if (startIdx !== -1 && endIdx !== -1) {
    // Replace existing block
    return existingContent.substring(0, startIdx) + pointerBlock + existingContent.substring(endIdx + endMarker.length);
  } else {
    // Append to end
    return existingContent.trimEnd() + '\n\n' + pointerBlock + '\n';
  }
}
