/**
 * Generate the content for .cotext/COTEXT_GUIDE.md
 * This is the single source of truth for agents working with this repo.
 */
export function generateCotextGuide(repoOwner: string, repoName: string, rooms: Array<{ path: string }>): string {
  const roomList = rooms.map(r => `- \`${r.path}\` → \`${r.path}/.cotext/cotext.md\``).join('\n');
  
  return `# COTEXT_GUIDE.md

> Auto-generated by Cotext. This file is the single source of truth for agents working with this repository.
> Do not edit manually — Cotext will overwrite on next sync.

---

## 📌 Quick Start

1. Read this guide
2. Read \`.cotext/INDEX.md\` for the room map
3. Read a room's \`cotext.md\` file
4. Append your notes with the correct source tag
5. Push changes back

---

## 1. What is Cotext?

Cotext is a **context engineering tool**. This repository (\`${repoOwner}/${repoName}\`) is a **context pool** — a structured collection of notes, decisions, and context blocks stored as markdown.

**The GitHub repo is the single source of truth.** All agents read from and write to the same pool.

### How Knowledge Flows

\`\`\`
┌─────────────────┐     ┌──────────────┐     ┌──────────────┐     ┌────────┐
│ AI Agent        │────▶│ cotext-mcp   │────▶│ context-api  │────▶│ GitHub │
│ (Claude/Cursor) │ MCP │ (npx)        │HTTPS│ (Edge Func)  │ API │  Repo  │
│                 │◀────│              │◀────│              │◀────│        │
└─────────────────┘     └──────────────┘     └──────────────┘     └────────┘

┌─────────────────┐                                                ┌────────┐
│ Web AI          │───────── HTTPS (REST API) ────────────────────▶│ GitHub │
│ (ChatGPT/Gemini)│◀──────────────────────────────────────────────│  Repo  │
└─────────────────┘                                                └────────┘

┌─────────────────┐         git push/pull                         ┌────────┐
│ Human           │────────────────────────────────────────────────│ GitHub │
│ (Cotext App)    │◀───────────────────────────────────────────────│  Repo  │
└─────────────────┘                                                └────────┘
\`\`\`

---

## 2. Repository Structure

\`\`\`
<directory>/.cotext/cotext.md   ← Context file (one per room)
<directory>/.cotext/assets/     ← Attached images and files
.cotext/COTEXT_GUIDE.md         ← This file (agent guide)
.cotext/INDEX.md                ← Room index and map
\`\`\`

### Active Rooms
${roomList || '- No rooms configured yet'}

---

## 3. Block Format

Each entry ("block") in a cotext.md file:

\`\`\`markdown
## YYYY-MM-DD HH:mm
<!-- source: me -->

Your content here (markdown).

Attachments:
- ![image](./assets/filename.webp)
\`\`\`

### Source Tags (Provenance)

| Tag | Who | Meaning |
|-----|-----|---------|
| \`source: me\` | Human | Written by human through Cotext UI |
| \`source: agent\` | Any AI | Generic AI-written content |
| \`source: claude\` | Claude | Written by Claude |
| \`source: chatgpt\` | ChatGPT | Written by ChatGPT |
| \`source: gemini\` | Gemini | Written by Gemini |
| \`source: antigravity\` | Antigravity | Written by Antigravity |

**Rule: Never omit the source tag.**

---

## 4. For MCP Agents (Claude Desktop, Cursor, Antigravity)

You have 5 tools available:

### Reading

| Tool | Purpose | Example |
|------|---------|---------|
| \`list_rooms\` | See all rooms | "Show me the rooms in this project" |
| \`get_room\` | Read a specific room | "Read the src/features room" |
| \`search_context\` | Search across all rooms | "Search for 'authentication'" |
| \`get_pack\` | Get human-only notes (Context Pack) | "Get my notes from root room" |

### Writing

| Tool | Purpose | Example |
|------|---------|---------|
| \`append_note\` | Add a new block to a room | "Save this decision to the root room" |

### Workflow Example

\`\`\`
1. list_rooms               → See what rooms exist
2. get_room("src/features") → Read existing context
3. (do your work)
4. append_note("src/features", "My analysis: ...", "claude")
                             → Save results back
\`\`\`

---

## 5. For Web AI Agents (ChatGPT, Gemini, Claude.ai)

Use the REST API with the provided API key:

### Reading

\`\`\`bash
# List rooms
GET /rooms
Authorization: Bearer ctx_xxx

# Read a room
GET /rooms/{ROOM_PATH}
Authorization: Bearer ctx_xxx

# Get human-only Context Pack
GET /pack/{ROOM_PATH}?source=me
Authorization: Bearer ctx_xxx

# Search
GET /search?q=keyword
Authorization: Bearer ctx_xxx
\`\`\`

### Writing

\`\`\`bash
# Append a block
POST /rooms/{ROOM_PATH}/append
Authorization: Bearer ctx_xxx
Content-Type: application/json

{"content": "Your markdown here", "source": "chatgpt"}
\`\`\`

---

## 6. Rules (All Agents)

1. **Always tag your source** — Use \`<!-- source: YOUR_NAME -->\` for every block
2. **Read before write** — Always read existing context before generating new content
3. **Append only** — Add new blocks at the end. Don't modify existing blocks
4. **Respect human content** — Blocks with \`source: me\` are primary. Don't summarize or rewrite
5. **Pull before push** — If using git directly, always pull latest first
6. **Markdown format** — All content must be valid markdown
`;
}

/**
 * Generate the content for .cotext/INDEX.md
 * A machine-readable map of rooms and their metadata.
 */
export function generateCotextIndex(repoOwner: string, repoName: string, rooms: Array<{ path: string; updatedAt?: string }>): string {
  const roomEntries = rooms.map(r => {
    const updated = r.updatedAt ? ` (updated: ${r.updatedAt.split('T')[0]})` : '';
    return `- [${r.path}](${r.path}/.cotext/cotext.md)${updated}`;
  }).join('\n');

  return `# Cotext Index — ${repoOwner}/${repoName}

> Auto-generated by Cotext. Do not edit manually.

## Rooms
${roomEntries || '- No rooms yet'}
`;
}

/**
 * Generate the thin pointer block for AGENTS.md or CLAUDE.md
 * Uses <!-- cotext:start --> markers for non-destructive updates.
 */
export function generateAgentsPointerBlock(): string {
  return `<!-- cotext:start -->
## Cotext Context Pool

This repository uses [Cotext](https://cotext-app.vercel.app) as a context engineering tool.

**Start here:** Read \`.cotext/COTEXT_GUIDE.md\` for structure, block format, and the mandatory pull/push protocol.

- Guide: \`.cotext/COTEXT_GUIDE.md\`
- Index: \`.cotext/INDEX.md\`
- Rooms: Each directory with \`.cotext/cotext.md\`
<!-- cotext:end -->`;
}

/**
 * Insert or update the Cotext pointer block in an existing file's content.
 * If markers exist, replace the block between them. Otherwise, append.
 */
export function upsertPointerBlock(existingContent: string, pointerBlock: string): string {
  const startMarker = '<!-- cotext:start -->';
  const endMarker = '<!-- cotext:end -->';
  const startIdx = existingContent.indexOf(startMarker);
  const endIdx = existingContent.indexOf(endMarker);

  if (startIdx !== -1 && endIdx !== -1) {
    // Replace existing block
    return existingContent.substring(0, startIdx) + pointerBlock + existingContent.substring(endIdx + endMarker.length);
  } else {
    // Append to end
    return existingContent.trimEnd() + '\n\n' + pointerBlock + '\n';
  }
}
