// youtube-transcript — fetch a YouTube video's caption track and return clean
// transcript text. Works for any public video that has captions (auto-generated
// or human-uploaded). No API key required.
//
// Why innertube instead of the watch page: YouTube flags Supabase Edge IPs as
// "datacenter" traffic and gates the watch HTML behind a bot check. The
// internal /youtubei/v1/player endpoint, however, accepts requests from the
// mobile/TV/embedded client contexts without that gate. We try several
// clients in order and pick the first one that returns a usable response.
//
// POST { url, lang? } → {
//   videoId, title, channel, durationSec, language, isAutoGenerated,
//   segments: [{ start, dur, text }],
//   fullText
// }

import { corsHeaders } from '../_shared/cors.ts';

interface ClientContext {
  name: string;
  clientName: string;
  clientNameId: string; // X-Youtube-Client-Name header value
  clientVersion: string;
  userAgent: string;
  deviceMake?: string;
  deviceModel?: string;
  osName?: string;
  osVersion?: string;
  hl?: string;
  gl?: string;
}

const CLIENTS: ClientContext[] = [
  {
    name: 'IOS',
    clientName: 'IOS', clientNameId: '5', clientVersion: '19.45.4',
    userAgent: 'com.google.ios.youtube/19.45.4 (iPhone16,2; U; CPU iOS 18_1_0 like Mac OS X;)',
    deviceMake: 'Apple', deviceModel: 'iPhone16,2', osName: 'iPhone', osVersion: '18.1.0.22B83',
    hl: 'en', gl: 'US',
  },
  {
    name: 'ANDROID',
    clientName: 'ANDROID', clientNameId: '3', clientVersion: '19.44.38',
    userAgent: 'com.google.android.youtube/19.44.38 (Linux; U; Android 14; en_US) gzip',
    deviceMake: 'Google', deviceModel: 'Pixel 8', osName: 'Android', osVersion: '14',
    hl: 'en', gl: 'US',
  },
  {
    name: 'TVHTML5_SIMPLY_EMBEDDED_PLAYER',
    clientName: 'TVHTML5_SIMPLY_EMBEDDED_PLAYER', clientNameId: '85', clientVersion: '2.0',
    userAgent: 'Mozilla/5.0 (PlayStation 4 5.55) AppleWebKit/601.2 (KHTML, like Gecko)',
    hl: 'en', gl: 'US',
  },
  {
    name: 'WEB_EMBEDDED_PLAYER',
    clientName: 'WEB_EMBEDDED_PLAYER', clientNameId: '56', clientVersion: '1.20241201.00.00',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
    hl: 'en', gl: 'US',
  },
  {
    name: 'MWEB',
    clientName: 'MWEB', clientNameId: '2', clientVersion: '2.20241201.01.00',
    userAgent: 'Mozilla/5.0 (Linux; Android 14; Pixel 8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36',
    hl: 'en', gl: 'US',
  },
];

interface CaptionTrack {
  baseUrl: string;
  languageCode: string;
  name?: { simpleText?: string };
  kind?: string;
  vssId?: string;
}

interface PickedTrack {
  baseUrl: string;
  languageCode: string;
  isAuto: boolean;
}

function extractVideoId(input: string): string | null {
  const trimmed = input.trim();
  if (/^[A-Za-z0-9_-]{11}$/.test(trimmed)) return trimmed;
  try {
    const u = new URL(trimmed);
    const host = u.hostname.replace(/^www\./, '');
    if (host === 'youtu.be') {
      const id = u.pathname.replace(/^\//, '').split('/')[0];
      return /^[A-Za-z0-9_-]{11}$/.test(id) ? id : null;
    }
    if (host.endsWith('youtube.com') || host === 'm.youtube.com') {
      const v = u.searchParams.get('v');
      if (v && /^[A-Za-z0-9_-]{11}$/.test(v)) return v;
      const segs = u.pathname.split('/').filter(Boolean);
      for (let i = 0; i < segs.length - 1; i += 1) {
        if (['shorts', 'live', 'embed', 'v'].includes(segs[i])) {
          const id = segs[i + 1];
          if (/^[A-Za-z0-9_-]{11}$/.test(id)) return id;
        }
      }
    }
  } catch { /* not a URL */ }
  return null;
}

function pickTrack(tracks: CaptionTrack[], preferred?: string): PickedTrack | null {
  if (!tracks?.length) return null;
  const ranked: CaptionTrack[] = [];
  const want = (preferred || '').toLowerCase();
  if (want) {
    const m = tracks.find((t) => t.languageCode?.toLowerCase().startsWith(want) && t.kind !== 'asr');
    if (m) ranked.push(m);
    const a = tracks.find((t) => t.languageCode?.toLowerCase().startsWith(want) && t.kind === 'asr');
    if (a) ranked.push(a);
  }
  const koM = tracks.find((t) => /^ko/i.test(t.languageCode) && t.kind !== 'asr');
  if (koM) ranked.push(koM);
  const koA = tracks.find((t) => /^ko/i.test(t.languageCode) && t.kind === 'asr');
  if (koA) ranked.push(koA);
  const enM = tracks.find((t) => /^en/i.test(t.languageCode) && t.kind !== 'asr');
  if (enM) ranked.push(enM);
  const enA = tracks.find((t) => /^en/i.test(t.languageCode) && t.kind === 'asr');
  if (enA) ranked.push(enA);
  ranked.push(...tracks.filter((t) => t.kind !== 'asr'));
  ranked.push(...tracks);
  const seen = new Set<string>();
  for (const t of ranked) {
    if (seen.has(t.baseUrl)) continue;
    seen.add(t.baseUrl);
    return { baseUrl: t.baseUrl, languageCode: t.languageCode, isAuto: t.kind === 'asr' };
  }
  return null;
}

function decodeXmlEntities(s: string): string {
  return s
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&apos;/g, "'")
    .replace(/&#(\d+);/g, (_, n) => String.fromCharCode(parseInt(n, 10)))
    .replace(/&#x([0-9a-f]+);/gi, (_, n) => String.fromCharCode(parseInt(n, 16)));
}

interface Segment { start: number; dur: number; text: string }

function parseTimedTextXml(xml: string): Segment[] {
  const out: Segment[] = [];
  const transcriptRe = /<text\s+([^>]*?)>([\s\S]*?)<\/text>/g;
  let m: RegExpExecArray | null;
  while ((m = transcriptRe.exec(xml)) !== null) {
    const attrs = m[1];
    const inner = m[2];
    const start = parseFloat((attrs.match(/start="([^"]+)"/) || [])[1] || '0');
    const dur = parseFloat((attrs.match(/dur="([^"]+)"/) || [])[1] || '0');
    const text = decodeXmlEntities(inner.replace(/<[^>]+>/g, '')).trim();
    if (text) out.push({ start, dur, text });
  }
  if (out.length > 0) return out;
  const pRe = /<p\s+([^>]*?)>([\s\S]*?)<\/p>/g;
  while ((m = pRe.exec(xml)) !== null) {
    const attrs = m[1];
    const inner = m[2];
    const startMs = parseInt((attrs.match(/\bt="([^"]+)"/) || [])[1] || '0', 10);
    const durMs = parseInt((attrs.match(/\bd="([^"]+)"/) || [])[1] || '0', 10);
    const text = decodeXmlEntities(inner.replace(/<[^>]+>/g, '')).trim();
    if (text) out.push({ start: startMs / 1000, dur: durMs / 1000, text });
  }
  return out;
}

interface PlayerResponse {
  playabilityStatus?: { status?: string; reason?: string };
  videoDetails?: {
    title?: string;
    author?: string;
    lengthSeconds?: string;
  };
  captions?: {
    playerCaptionsTracklistRenderer?: {
      captionTracks?: CaptionTrack[];
    };
  };
}

async function callInnertube(client: ClientContext, videoId: string): Promise<PlayerResponse> {
  const body = {
    context: {
      client: {
        hl: client.hl || 'en',
        gl: client.gl || 'US',
        clientName: client.clientName,
        clientVersion: client.clientVersion,
        ...(client.deviceMake ? { deviceMake: client.deviceMake } : {}),
        ...(client.deviceModel ? { deviceModel: client.deviceModel } : {}),
        ...(client.osName ? { osName: client.osName } : {}),
        ...(client.osVersion ? { osVersion: client.osVersion } : {}),
        userAgent: client.userAgent,
      },
    },
    videoId,
    contentCheckOk: true,
    racyCheckOk: true,
    playbackContext: { contentPlaybackContext: { html5Preference: 'HTML5_PREF_WANTS' } },
  };
  const res = await fetch('https://www.youtube.com/youtubei/v1/player?prettyPrint=false', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'User-Agent': client.userAgent,
      'X-Youtube-Client-Name': client.clientNameId,
      'X-Youtube-Client-Version': client.clientVersion,
      'Accept-Language': `${client.hl || 'en'},${client.hl || 'en'};q=0.9`,
      'Origin': 'https://www.youtube.com',
      'Referer': 'https://www.youtube.com/',
    },
    body: JSON.stringify(body),
  });
  if (!res.ok) throw new Error(`innertube[${client.name}] ${res.status}`);
  return await res.json() as PlayerResponse;
}

interface ResolveResult {
  player: PlayerResponse;
  clientUsed: string;
}

async function resolvePlayer(videoId: string): Promise<ResolveResult> {
  let lastErr: Error | null = null;
  let lastBlocked: PlayerResponse | null = null;
  for (const client of CLIENTS) {
    try {
      const player = await callInnertube(client, videoId);
      const status = player.playabilityStatus?.status;
      // OK or UNPLAYABLE-but-with-captions both qualify (some embeds report
      // UNPLAYABLE while still exposing the caption tracklist).
      if (!status || status === 'OK' || status === 'CONTENT_CHECK_REQUIRED') {
        const tracks = player.captions?.playerCaptionsTracklistRenderer?.captionTracks;
        if (tracks && tracks.length > 0) {
          return { player, clientUsed: client.name };
        }
        // No captions on this client — try next in case a different client
        // exposes them.
        lastBlocked = player;
        continue;
      }
      // Blocked / login-required — remember and try another client.
      lastBlocked = player;
    } catch (err) {
      lastErr = err instanceof Error ? err : new Error(String(err));
    }
  }
  if (lastBlocked) {
    const e = new Error(
      `All innertube clients failed: ${lastBlocked.playabilityStatus?.reason || lastBlocked.playabilityStatus?.status || 'no captions exposed'}`,
    );
    (e as Error & { player?: PlayerResponse }).player = lastBlocked;
    throw e;
  }
  throw lastErr || new Error('No innertube client returned a response');
}

// ─── Fallback path 1: legacy /api/timedtext list endpoint (pre-2018) ──
// This endpoint sometimes survives bot-check IP gates because it predates
// the modern auth scheme. Doesn't list auto-generated tracks though.
interface LegacyTrack { lang_code: string; kind?: string; name?: string }

async function legacyListTracks(videoId: string): Promise<LegacyTrack[]> {
  const listUrl = `https://www.youtube.com/api/timedtext?type=list&v=${videoId}`;
  const res = await fetch(listUrl, {
    headers: { 'User-Agent': CLIENTS[0].userAgent, 'Accept-Language': 'en-US,en;q=0.9' },
  });
  if (!res.ok) return [];
  const xml = await res.text();
  if (!xml.includes('<track')) return [];
  const tracks: LegacyTrack[] = [];
  const re = /<track\s+([^>]*?)\/?>/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(xml)) !== null) {
    const attrs = m[1];
    const lang = (attrs.match(/lang_code="([^"]+)"/) || [])[1];
    if (!lang) continue;
    tracks.push({
      lang_code: lang,
      kind: (attrs.match(/\bkind="([^"]+)"/) || [])[1],
      name: (attrs.match(/\bname="([^"]*)"/) || [])[1],
    });
  }
  return tracks;
}

function pickLegacy(tracks: LegacyTrack[], preferred?: string): LegacyTrack | null {
  if (tracks.length === 0) return null;
  const want = (preferred || '').toLowerCase();
  if (want) {
    const hit = tracks.find((t) => t.lang_code.toLowerCase().startsWith(want));
    if (hit) return hit;
  }
  return tracks.find((t) => /^ko/i.test(t.lang_code))
    || tracks.find((t) => /^en/i.test(t.lang_code))
    || tracks[0];
}

// ─── Fallback path 2: Supadata (paid 3rd party) ──────────────────────
// Set env vars SUPADATA_API_KEY / SUPADATA_API_KEY_BACKUP_1 / _BACKUP_2 to enable.
// Free tier: 100 req/mo per key. We rotate on quota-exhaustion (HTTP 402/429)
// or other failures so multiple keys give us a bigger combined quota.
// Returns: { result, exhausted } — when all keys hit quota, exhausted=true so
// the caller can decide to surface a manual fallback link.
const NOTEGPT_URL = 'https://notegpt.io/youtube-transcript-generator';

interface SupadataResult {
  fullText: string; segments: Segment[]; language: string; isAutoGenerated: boolean;
}

async function supadataTryOne(videoId: string, lang: string | undefined, apiKey: string): Promise<
  { ok: true; data: SupadataResult } | { ok: false; status: number; exhausted: boolean; msg: string }
> {
  const url = `https://api.supadata.ai/v1/youtube/transcript?videoId=${videoId}${lang ? `&lang=${lang}` : ''}&text=false`;
  const res = await fetch(url, { headers: { 'x-api-key': apiKey } });
  if (!res.ok) {
    const txt = await res.text().catch(() => '');
    // 402 = payment required (quota), 429 = rate limit. Treat as exhausted so
    // we move to the next key.
    const exhausted = res.status === 402 || res.status === 429
      || /quota|limit|insufficient/i.test(txt);
    return { ok: false, status: res.status, exhausted, msg: txt.slice(0, 200) };
  }
  const data = await res.json().catch(() => null) as {
    content?: Array<{ text: string; offset: number; duration: number }>;
    lang?: string;
    availableLangs?: string[];
  } | null;
  if (!data?.content?.length) {
    return { ok: false, status: 200, exhausted: false, msg: 'empty response' };
  }
  const segments: Segment[] = data.content.map((c) => ({
    start: (c.offset || 0) / 1000,
    dur: (c.duration || 0) / 1000,
    text: c.text || '',
  }));
  return {
    ok: true,
    data: {
      segments,
      fullText: segments.map((s) => s.text).join(' ').replace(/\s+/g, ' ').trim(),
      language: data.lang || lang || 'unknown',
      isAutoGenerated: false,
    },
  };
}

interface SupadataChainResult {
  result?: SupadataResult;
  exhausted: boolean; // true if ALL configured keys returned quota/limit errors
  triedSummary: string[]; // per-attempt summary for debug
  keyUsedIndex?: number;
}

async function supadataChain(videoId: string, lang: string | undefined): Promise<SupadataChainResult> {
  const keys = [
    Deno.env.get('SUPADATA_API_KEY'),
    Deno.env.get('SUPADATA_API_KEY_BACKUP_1'),
    Deno.env.get('SUPADATA_API_KEY_BACKUP_2'),
  ].filter((k): k is string => !!k && k.trim().length > 0);
  if (keys.length === 0) return { exhausted: false, triedSummary: ['supadata:no-key'] };

  const triedSummary: string[] = [];
  let allExhausted = true;
  for (let i = 0; i < keys.length; i += 1) {
    const tag = `key#${i + 1}`;
    try {
      const r = await supadataTryOne(videoId, lang, keys[i]);
      if (r.ok) {
        triedSummary.push(`supadata:${tag}:ok`);
        return { result: r.data, exhausted: false, triedSummary, keyUsedIndex: i };
      }
      triedSummary.push(`supadata:${tag}:fail(${r.status}${r.exhausted ? ',quota' : ''})`);
      if (!r.exhausted) allExhausted = false;
    } catch (err) {
      triedSummary.push(`supadata:${tag}:err(${err instanceof Error ? err.message : String(err)})`);
      allExhausted = false;
    }
  }
  return { exhausted: allExhausted, triedSummary };
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders });
  const json = (status: number, body: unknown) => new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
  });

  try {
    const body = await req.json().catch(() => ({}));
    const url = typeof body.url === 'string' ? body.url : '';
    const lang = typeof body.lang === 'string' ? body.lang : '';
    const videoId = extractVideoId(url);
    if (!videoId) return json(400, { error: 'Invalid YouTube URL or video ID' });

    const debug: { tried: string[]; lastError?: string; lastStatus?: string } = { tried: [] };

    // 1) Get player response via innertube (multi-client fallback).
    let resolved: ResolveResult | null = null;
    try {
      resolved = await resolvePlayer(videoId);
      debug.tried.push(`innertube:${resolved.clientUsed}:ok`);
    } catch (err) {
      const e = err as Error & { player?: PlayerResponse };
      debug.lastError = e.message;
      debug.lastStatus = e.player?.playabilityStatus?.status;
      debug.tried.push(`innertube:all-failed(${debug.lastStatus || 'no-response'})`);
    }

    const success = (extra: Record<string, unknown>) => json(200, { ok: true, ...extra });

    // 2) Legacy /api/timedtext fallback — free, sometimes works when innertube
    //    is bot-checked. Doesn't list auto-generated tracks, so it only helps
    //    videos with manual captions.
    if (!resolved) {
      try {
        const legacy = await legacyListTracks(videoId);
        if (legacy.length > 0) {
          const picked = pickLegacy(legacy, lang);
          if (picked) {
            const capUrl = `https://www.youtube.com/api/timedtext?lang=${picked.lang_code}&v=${videoId}${picked.kind ? `&kind=${picked.kind}` : ''}${picked.name ? `&name=${encodeURIComponent(picked.name)}` : ''}`;
            const capRes = await fetch(capUrl, { headers: { 'User-Agent': CLIENTS[0].userAgent } });
            if (capRes.ok) {
              const segs = parseTimedTextXml(await capRes.text());
              if (segs.length > 0) {
                debug.tried.push('legacy-timedtext:ok');
                const fullText = segs.map((s) => s.text).join(' ').replace(/\s+/g, ' ').trim();
                const last = segs[segs.length - 1];
                return success({
                  videoId,
                  title: '',
                  channel: '',
                  durationSec: Math.ceil(last.start + last.dur),
                  language: picked.lang_code,
                  isAutoGenerated: picked.kind === 'asr',
                  segments: segs,
                  fullText,
                  sourceUrl: `https://www.youtube.com/watch?v=${videoId}`,
                  clientUsed: 'legacy-timedtext',
                  debug,
                });
              }
            }
          }
        }
        debug.tried.push('legacy-timedtext:no-tracks');
      } catch (err) {
        debug.tried.push(`legacy-timedtext:err(${err instanceof Error ? err.message : String(err)})`);
      }
    }

    // 3) Supadata fallback — paid 3rd party, with multi-key rotation.
    let supadataExhausted = false;
    if (!resolved) {
      const chain = await supadataChain(videoId, lang);
      debug.tried.push(...chain.triedSummary);
      if (chain.result) {
        const sd = chain.result;
        const last = sd.segments[sd.segments.length - 1];
        return success({
          videoId,
          title: '',
          channel: '',
          durationSec: last ? Math.ceil(last.start + last.dur) : 0,
          language: sd.language,
          isAutoGenerated: sd.isAutoGenerated,
          segments: sd.segments,
          fullText: sd.fullText,
          sourceUrl: `https://www.youtube.com/watch?v=${videoId}`,
          clientUsed: `supadata:key#${(chain.keyUsedIndex ?? 0) + 1}`,
          debug,
        });
      }
      supadataExhausted = chain.exhausted;
    }

    if (!resolved) {
      // Out of automated options — surface the noteGPT manual fallback link
      // so the user can finish the job in one click.
      return json(200, {
        ok: false,
        error: supadataExhausted
          ? 'YouTube transcript service is currently rate-limited. Use the manual fallback link below.'
          : 'YouTube blocked this request from our server IP. Try the manual fallback link below.',
        playabilityStatus: debug.lastStatus || 'BLOCKED',
        videoId,
        fallbackUrl: NOTEGPT_URL,
        debug,
      });
    }

    const { player, clientUsed } = resolved;

    const details = player.videoDetails || {};
    const tracks = player.captions?.playerCaptionsTracklistRenderer?.captionTracks;
    if (!tracks || tracks.length === 0) {
      return json(404, {
        error: 'No captions available for this video',
        videoId,
        title: details.title,
        channel: details.author,
        clientUsed,
      });
    }

    const picked = pickTrack(tracks, lang);
    if (!picked) return json(404, { error: 'No usable caption track found', clientUsed });

    // 2) Fetch caption XML. Append fmt=srv3 hint (some hosts return JSON3 by
    // default which our parser doesn't read).
    const captionUrl = picked.baseUrl.includes('&fmt=') ? picked.baseUrl : `${picked.baseUrl}&fmt=srv3`;
    const captionRes = await fetch(captionUrl, {
      headers: {
        'User-Agent': CLIENTS[0].userAgent,
        'Accept-Language': 'en-US,en;q=0.9',
      },
    });
    if (!captionRes.ok) {
      return json(502, { error: `Caption fetch failed (${captionRes.status})`, clientUsed });
    }
    const xml = await captionRes.text();
    let segments = parseTimedTextXml(xml);

    // Fallback: try without fmt hint if first attempt returned nothing.
    if (segments.length === 0) {
      const altRes = await fetch(picked.baseUrl, { headers: { 'User-Agent': CLIENTS[0].userAgent } });
      if (altRes.ok) segments = parseTimedTextXml(await altRes.text());
    }
    if (segments.length === 0) {
      return json(502, { error: 'Caption track returned no parseable text', length: xml.length, clientUsed });
    }

    const fullText = segments.map((s) => s.text).join(' ').replace(/\s+/g, ' ').trim();
    const last = segments[segments.length - 1];
    const durationSec = parseInt(details.lengthSeconds || '0', 10) || Math.ceil(last.start + last.dur);

    return success({
      videoId,
      title: details.title || '',
      channel: details.author || '',
      durationSec,
      language: picked.languageCode,
      isAutoGenerated: picked.isAuto,
      segments,
      fullText,
      sourceUrl: `https://www.youtube.com/watch?v=${videoId}`,
      clientUsed,
      debug,
    });
  } catch (err) {
    return json(500, { error: err instanceof Error ? err.message : String(err) });
  }
});
