/**
 * YouTubeImportModal — paste a YouTube link, pull the caption track via the
 * `youtube-transcript` Edge Function, optionally polish through an LLM, then
 * drop the cleaned text into the composer.
 *
 * Composer integration: `onInsert(text)` receives the chosen output and the
 * composer prepends it to the current input.
 */

import { useCallback, useEffect, useMemo, useState } from 'react';
import { X, YoutubeLogo, Spinner as Loader2, ClipboardText, ArrowSquareOut } from '@phosphor-icons/react';
import { youtubeTranscriptApi, type YouTubeTranscriptSuccess } from '../lib/supabase/functions';
import { getKey } from '../lib/agent/keys';
import { PROVIDERS, getProvider, type ProviderId } from '../lib/agent/models';
import { runChat } from '../lib/agent/providers';

interface Props {
  open: boolean;
  language: 'ko' | 'en';
  onClose: () => void;
  onInsert: (text: string) => void;
}

type FormatChoice = 'plain' | 'timestamped' | 'cleanup' | 'summary';
type Phase = 'idle' | 'fetching' | 'fetched' | 'polishing' | 'error';

const AI_CHOICES: FormatChoice[] = ['cleanup', 'summary'];

function formatTimestamp(sec: number): string {
  const total = Math.max(0, Math.floor(sec));
  const m = Math.floor(total / 60);
  const s = total % 60;
  return `${m.toString().padStart(2, '0')}:${s.toString().padStart(2, '0')}`;
}

function formatDuration(sec: number): string {
  if (!sec) return '';
  const h = Math.floor(sec / 3600);
  const m = Math.floor((sec % 3600) / 60);
  const s = sec % 60;
  return h > 0
    ? `${h}:${m.toString().padStart(2, '0')}:${s.toString().padStart(2, '0')}`
    : `${m}:${s.toString().padStart(2, '0')}`;
}

function buildPlain(t: YouTubeTranscriptSuccess): string {
  return [
    `> 📺 [${t.title || t.videoId}](${t.sourceUrl}) — ${t.channel || 'YouTube'}`,
    '',
    t.fullText,
  ].join('\n');
}

function buildTimestamped(t: YouTubeTranscriptSuccess): string {
  const lines: string[] = [
    `> 📺 [${t.title || t.videoId}](${t.sourceUrl}) — ${t.channel || 'YouTube'} · ${formatDuration(t.durationSec)}`,
    '',
  ];
  for (const seg of t.segments) {
    lines.push(`- [${formatTimestamp(seg.start)}] ${seg.text}`);
  }
  return lines.join('\n');
}

// ─── Cleanup preset: preserve everything, just polish ────────────────
const CLEANUP_SYSTEM = `You clean up a YouTube transcript so it reads like a well-edited
article — NOT a summary. Your job:
- Fix obvious caption errors (misheard words, dropped punctuation, run-on sentences).
- Add structure: paragraph breaks, headings, bullet lists where the speaker is
  clearly enumerating. Use markdown.
- KEEP all substantive content. Do not summarize, do not omit examples, anecdotes,
  numbers, names, quotes, or technical detail. The output should be roughly the
  same length as the input (in words), not shorter.
- The only things you may drop are pure filler ("음", "어", "그", "you know",
  repeated stutters) and obvious caption duplicates from auto-subtitle quirks.
- Stay in the SAME language as the input.
- Output markdown only — no preamble, no "Here is the cleaned transcript:" intro.`;

// ─── Summary preset: condensed key points ────────────────────────────
const SUMMARY_SYSTEM = `You produce a concise, structured summary of a YouTube transcript.
Output shape:
1. **한 줄 요약 / TL;DR** — one sentence capturing the central message.
2. **핵심 포인트 / Key points** — 4-8 bullet points, each one tight sentence.
   Cover the most important arguments, claims, numbers, or steps in order.
3. **눈에 띄는 인용 / Notable quotes** (only if there are 1-3 genuinely
   striking lines worth quoting; otherwise skip this section).
4. **그래서 뭐 / So what** — 1-2 sentences on the practical takeaway or
   why this matters.

Rules:
- Stay in the SAME language as the input (Korean transcript → Korean summary).
- Use markdown headings (##) for each section.
- Be specific: prefer concrete details over generic abstractions.
- Output markdown only — no preamble, no meta commentary.`;

function buildAiPrompt(t: YouTubeTranscriptSuccess, mode: 'cleanup' | 'summary'): string {
  const MAX = 60000;
  const body = t.fullText.length > MAX
    ? `${t.fullText.slice(0, MAX)}\n\n[... transcript truncated at ${MAX.toLocaleString()} chars; ${mode === 'summary' ? 'summarize what is shown' : 'clean what is shown and end naturally'} ...]`
    : t.fullText;

  const task = mode === 'cleanup'
    ? 'Clean this transcript into a readable article-style markdown document. Preserve all substantive content — do NOT summarize.'
    : 'Summarize this transcript using the section structure defined in the system prompt.';

  return `TITLE: ${t.title || '(no title)'}
CHANNEL: ${t.channel || '(unknown)'}
DURATION: ${formatDuration(t.durationSec)}
LANGUAGE: ${t.language}${t.isAutoGenerated ? ' (auto-generated, may have errors)' : ''}

TRANSCRIPT:
${body}

${task}
End with a source line on its own:
\`출처: [${t.title || t.videoId}](${t.sourceUrl})\``;
}

const FORMAT_LABELS: Record<FormatChoice, { ko: string; en: string }> = {
  plain: { ko: '원문 그대로', en: 'Plain text' },
  timestamped: { ko: '타임스탬프 포함', en: 'With timestamps' },
  cleanup: { ko: 'AI 내용 정리', en: 'AI cleanup' },
  summary: { ko: 'AI 핵심 요약', en: 'AI key summary' },
};

export default function YouTubeImportModal({ open, language, onClose, onInsert }: Props) {
  const ko = language === 'ko';
  const [url, setUrl] = useState('');
  const [phase, setPhase] = useState<Phase>('idle');
  const [error, setError] = useState<string | null>(null);
  const [fallbackUrl, setFallbackUrl] = useState<string | null>(null);
  const [transcript, setTranscript] = useState<YouTubeTranscriptSuccess | null>(null);
  const [formatChoice, setFormatChoice] = useState<FormatChoice>('plain');

  const availableProviders = useMemo(
    () => PROVIDERS.filter((p) => getKey(p.id).trim().length > 0),
    [open],
  );
  const [providerId, setProviderId] = useState<ProviderId>(() => availableProviders[0]?.id || 'gemini');
  const [model, setModel] = useState<string>(() => (availableProviders[0] ? availableProviders[0].defaultModel : ''));

  useEffect(() => {
    if (!open) return;
    setUrl('');
    setPhase('idle');
    setError(null);
    setFallbackUrl(null);
    setTranscript(null);
    setFormatChoice('plain');
    if (availableProviders[0]) {
      setProviderId(availableProviders[0].id);
      setModel(availableProviders[0].defaultModel);
    }
  }, [open, availableProviders]);

  const handleFetch = useCallback(async () => {
    if (!url.trim()) return;
    setPhase('fetching');
    setError(null);
    setFallbackUrl(null);
    setTranscript(null);
    try {
      const res = await youtubeTranscriptApi.fetch(url.trim());
      if (res.ok) {
        setTranscript(res);
        setPhase('fetched');
      } else {
        setError(res.error || (ko ? '스크립트를 가져오지 못했습니다.' : 'Failed to fetch transcript.'));
        if (res.fallbackUrl) setFallbackUrl(res.fallbackUrl);
        setPhase('error');
      }
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      setError(msg);
      setPhase('error');
    }
  }, [url, ko]);

  const handleInsert = useCallback(async () => {
    if (!transcript) return;
    if (formatChoice === 'plain') {
      onInsert(buildPlain(transcript));
      onClose();
      return;
    }
    if (formatChoice === 'timestamped') {
      onInsert(buildTimestamped(transcript));
      onClose();
      return;
    }
    // AI cleanup or summary
    const key = getKey(providerId);
    if (!key) {
      setError(ko ? '선택한 모델의 API 키가 없습니다.' : 'No API key set for the selected model.');
      return;
    }
    setPhase('polishing');
    setError(null);
    try {
      const provider = getProvider(providerId);
      const system = formatChoice === 'summary' ? SUMMARY_SYSTEM : CLEANUP_SYSTEM;
      const result = await runChat({
        shape: provider.shape,
        baseURL: provider.baseURL,
        apiKey: key,
        model: model || provider.defaultModel,
        system,
        messages: [{ role: 'user', content: buildAiPrompt(transcript, formatChoice as 'cleanup' | 'summary') }],
      });
      const polished = result.trim() || transcript.fullText;
      onInsert([
        `> 📺 [${transcript.title || transcript.videoId}](${transcript.sourceUrl}) — ${transcript.channel || 'YouTube'}`,
        '',
        polished,
      ].join('\n'));
      onClose();
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
      setPhase('fetched');
    }
  }, [transcript, formatChoice, providerId, model, onInsert, onClose, ko]);

  if (!open) return null;

  return (
    <div className="modal-overlay youtube-modal-overlay" onClick={onClose}>
      <div className="modal-content youtube-modal" onClick={(e) => e.stopPropagation()}>
        <div className="youtube-modal-header">
          <h3>
            <YoutubeLogo size={18} weight="fill" style={{ color: '#ff0000' }} />
            {ko ? 'YouTube 스크립트 가져오기' : 'Import YouTube transcript'}
          </h3>
          <button className="btn btn-ghost btn-sm" onClick={onClose}>
            <X size={14} />
          </button>
        </div>

        <div className="youtube-modal-body">
          <div className="youtube-url-row">
            <input
              className="youtube-url-input"
              value={url}
              onChange={(e) => setUrl(e.target.value)}
              onKeyDown={(e) => { if (e.key === 'Enter') handleFetch(); }}
              placeholder="https://www.youtube.com/watch?v=..."
              autoFocus
            />
            <button
              className="btn btn-primary"
              onClick={handleFetch}
              disabled={!url.trim() || phase === 'fetching' || phase === 'polishing'}
            >
              {phase === 'fetching' ? <Loader2 size={14} className="spin" /> : <ClipboardText size={14} />}
              {ko ? '가져오기' : 'Fetch'}
            </button>
          </div>

          {error && (
            <div className="youtube-error">
              <div>{error}</div>
              {fallbackUrl && (
                <a
                  className="youtube-fallback-link"
                  href={fallbackUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <ArrowSquareOut size={14} />
                  {ko
                    ? 'noteGPT에서 직접 변환하기 (새 창)'
                    : 'Convert manually on noteGPT (new tab)'}
                </a>
              )}
            </div>
          )}

          {transcript && (
            <>
              <div className="youtube-meta-card">
                <div className="youtube-meta-title">{transcript.title || transcript.videoId}</div>
                <div className="youtube-meta-line">
                  <span>{transcript.channel || '—'}</span>
                  <span>·</span>
                  <span>{formatDuration(transcript.durationSec)}</span>
                  <span>·</span>
                  <span>{transcript.language}{transcript.isAutoGenerated ? ' (auto)' : ''}</span>
                  <span>·</span>
                  <span>{transcript.segments.length} {ko ? '구간' : 'segments'}</span>
                </div>
              </div>

              <div className="youtube-preview">
                <label>
                  {ko ? '미리보기' : 'Preview'}
                  <span className="youtube-preview-count">
                    {transcript.fullText.length.toLocaleString()} {ko ? '자' : 'chars'}
                  </span>
                </label>
                <div className="youtube-preview-text">{transcript.fullText}</div>
              </div>

              <div className="youtube-format-group">
                <label>{ko ? '삽입 형식' : 'Insert format'}</label>
                <div className="youtube-format-options">
                  {(['plain', 'timestamped', 'cleanup', 'summary'] as FormatChoice[]).map((choice) => {
                    const requiresAi = AI_CHOICES.includes(choice);
                    const disabled = requiresAi && availableProviders.length === 0;
                    return (
                      <label
                        key={choice}
                        className={`youtube-format-option ${disabled ? 'is-disabled' : ''} ${formatChoice === choice ? 'is-active' : ''}`}
                        title={disabled ? (ko ? 'BYOK API 키 필요' : 'BYOK API key required') : undefined}
                      >
                        <input
                          type="radio"
                          name="yt-format"
                          checked={formatChoice === choice}
                          onChange={() => setFormatChoice(choice)}
                          disabled={disabled}
                        />
                        <span>{FORMAT_LABELS[choice][ko ? 'ko' : 'en']}</span>
                      </label>
                    );
                  })}
                </div>

                {AI_CHOICES.includes(formatChoice) && availableProviders.length > 0 && (
                  <div className="youtube-model-picker">
                    <select
                      value={providerId}
                      onChange={(e) => {
                        const next = e.target.value as ProviderId;
                        setProviderId(next);
                        setModel(getProvider(next).defaultModel);
                      }}
                    >
                      {availableProviders.map((p) => (
                        <option key={p.id} value={p.id}>{p.label}</option>
                      ))}
                    </select>
                    <select value={model} onChange={(e) => setModel(e.target.value)}>
                      {getProvider(providerId).models.map((m) => (
                        <option key={m} value={m}>{m}</option>
                      ))}
                    </select>
                  </div>
                )}
                {AI_CHOICES.includes(formatChoice) && (
                  <p className="youtube-hint">
                    {formatChoice === 'cleanup'
                      ? (ko
                        ? '오타·필러 제거하고 문단/제목/리스트로 구조화. 내용 전체 보존.'
                        : 'Fix typos/filler, structure into paragraphs/headings/lists. Preserves full content.')
                      : (ko
                        ? '한 줄 요약 + 핵심 포인트 + 눈에 띄는 인용 + 시사점으로 압축.'
                        : 'One-line TL;DR + key points + notable quotes + so-what.')}
                  </p>
                )}
                {AI_CHOICES.includes(formatChoice) && availableProviders.length === 0 && (
                  <p className="youtube-hint">
                    {ko
                      ? 'AI 옵션은 설정에서 BYOK 키(Gemini, OpenAI 등)를 먼저 등록해야 사용할 수 있습니다.'
                      : 'AI options require a BYOK key (Gemini, OpenAI, etc.) in settings first.'}
                  </p>
                )}
              </div>
            </>
          )}
        </div>

        <div className="youtube-modal-footer">
          <button className="btn btn-ghost" onClick={onClose}>
            {ko ? '취소' : 'Cancel'}
          </button>
          <button
            className="btn btn-primary"
            disabled={!transcript || phase === 'fetching' || phase === 'polishing'}
            onClick={handleInsert}
          >
            {phase === 'polishing' ? (
              <>
                <Loader2 size={14} className="spin" />
                {ko ? 'AI 정리 중…' : 'Polishing…'}
              </>
            ) : (
              <>{ko ? '채팅에 삽입' : 'Insert into chat'}</>
            )}
          </button>
        </div>
      </div>
    </div>
  );
}
