// ============================================================
// Neural Link — .cotext/NEURAL_INDEX.md generator (P5.4)
// 결정 D-009 / 계획서 §32 / concepts: neural-link-mcp-grounding (option C)
//
// 같은 패턴(COTEXT_GUIDE.md/INDEX.md)으로 push 시 자동 생성/갱신.
// 어떤 MCP/에이전트든 이 한 파일만 읽어도 그래프 구조를 사람·기계 모두
// 읽을 수 있는 markdown 표로 파악 가능 (시스템 프롬프트 grounding 무료).
// ============================================================

import type { NeuralGraph } from './types';

const NEURAL_INDEX_PATH = 'NEURAL_INDEX.md';

export function neuralIndexFilePath(cotextFolder = '.cotext'): string {
  return `${cotextFolder.replace(/\/$/, '')}/${NEURAL_INDEX_PATH}`;
}

/**
 * Produce a deterministic, agent-friendly markdown rendering of the graph.
 * - Sorted by size / label so diffs stay minimal between pushes.
 * - Empty graph yields a short stub so the file exists once neural data starts to land.
 */
export function generateNeuralIndex(graph: NeuralGraph, repoLabel?: string): string {
  const totalNodes = graph.nodes.length;
  const totalClusters = graph.clusters.length;
  const totalEdges = graph.edges.length;

  const lines: string[] = [];
  lines.push('# NEURAL_INDEX.md');
  lines.push('');
  lines.push('> Auto-generated by Cotext. Agent-readable snapshot of the Neural Link graph.');
  lines.push('> Do not edit manually — overwritten on next sync.');
  if (repoLabel) lines.push(`> Repo: \`${repoLabel}\``);
  lines.push('');
  lines.push('---');
  lines.push('');

  // ---- How to use ----
  lines.push('## How agents should use this file');
  lines.push('');
  lines.push('- **Nodes** are labeled thought-units anchored to a markdown block (a `## YYYY-MM-DD HH:mm` block inside a room\'s `cotext.md`).');
  lines.push('- **Clusters** are typed groups of nodes (think tags but first-class).');
  lines.push('- **Edges** are explicit node↔node relationships: `relates` (general), `supersedes` (this replaces that), `supports` (this backs that up).');
  lines.push('- Two nodes in the same cluster are implicitly related; an explicit edge is a stronger claim.');
  lines.push('- Each block carries a `<!-- source: me|claude|chatgpt|...; author: github-user -->` provenance tag — prefer `me` blocks as primary intent.');
  lines.push('');
  lines.push('When asked about a topic, first match against cluster names below, then fan out to the nodes inside.');
  lines.push('');

  // ---- Summary ----
  lines.push('## Summary');
  lines.push('');
  lines.push(`- Nodes: **${totalNodes}**`);
  lines.push(`- Clusters: **${totalClusters}**`);
  lines.push(`- Edges: **${totalEdges}**`);
  if (totalNodes === 0) {
    lines.push('');
    lines.push('_No nodes yet. Nodify a block in the Cotext app to seed this graph._');
    lines.push('');
    return lines.join('\n');
  }
  lines.push('');

  // ---- Clusters ----
  const sortedClusters = [...graph.clusters].sort((a, b) => a.id.localeCompare(b.id));
  const clusteredIds = new Set<string>();

  lines.push('## Clusters');
  lines.push('');
  if (sortedClusters.length === 0) {
    lines.push('_No clusters yet._');
    lines.push('');
  } else {
    for (const c of sortedClusters) {
      const members = graph.nodes
        .filter((n) => n.clusters.includes(c.id))
        .sort((a, b) => (a.label || a.id).localeCompare(b.label || b.id));
      members.forEach((m) => clusteredIds.add(m.id));
      const escName = mdEscape(c.name);
      lines.push(`### ${escName} \`${c.id}\` (${members.length} node${members.length === 1 ? '' : 's'})`);
      if (c.desc) lines.push(`> ${mdEscape(c.desc)}`);
      lines.push('');
      if (members.length === 0) {
        lines.push('_(no members yet)_');
        lines.push('');
        continue;
      }
      lines.push('| Node | Label | Room | Block | Source |');
      lines.push('|---|---|---|---|---|');
      for (const n of members) {
        lines.push(`| \`${n.id}\` | ${mdEscape(n.label || '(no label)')} | \`${n.room}\` | \`${n.blockTs}\` | ${n.source ?? '_n/a_'} |`);
      }
      lines.push('');
    }
  }

  // ---- Explicit node↔node edges ----
  lines.push('## Explicit edges');
  lines.push('');
  if (graph.edges.length === 0) {
    lines.push('_No explicit edges yet — relationships are implicit via shared clusters above._');
    lines.push('');
  } else {
    const labelOf = (id: string) => graph.nodes.find((n) => n.id === id)?.label || id;
    const sortedEdges = [...graph.edges].sort((a, b) => a.from.localeCompare(b.from) || a.to.localeCompare(b.to));
    lines.push('| From | → | To | Type |');
    lines.push('|---|---|---|---|');
    for (const e of sortedEdges) {
      const t = e.type ?? '_relates_';
      lines.push(`| \`${e.from}\` (${mdEscape(labelOf(e.from))}) | → | \`${e.to}\` (${mdEscape(labelOf(e.to))}) | ${t} |`);
    }
    lines.push('');
  }

  // ---- Unclustered nodes (orphan section, helps cleanup) ----
  const orphans = graph.nodes.filter((n) => !clusteredIds.has(n.id))
    .sort((a, b) => (a.label || a.id).localeCompare(b.label || b.id));
  if (orphans.length > 0) {
    lines.push('## Unclustered nodes');
    lines.push('');
    lines.push('| Node | Label | Room | Block |');
    lines.push('|---|---|---|---|');
    for (const n of orphans) {
      lines.push(`| \`${n.id}\` | ${mdEscape(n.label || '(no label)')} | \`${n.room}\` | \`${n.blockTs}\` |`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

/** Escape pipe/backtick so table rows don't break. */
function mdEscape(s: string): string {
  return s.replace(/\|/g, '\\|').replace(/`/g, "'");
}
